In [9]:
import tensorflow as tf

from numpy.random import RandomState

# Define batch size
batch_size = 8

# Define variables 'w1' and 'w2' and set random_seed for keeping every run result same
w1 = tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2 = tf.Variable(tf.truncated_normal([3,1],stddev=1,seed=1))

# Define the input and ground truth
x = tf.placeholder(tf.float32,shape=[None,2],name='x_input')
y_ = tf.placeholder(tf.float32,shape=[None,1],name='y_input')

# Define the forward-propagation of neural network
a = tf.matmul(x,w1)
y = tf.matmul(a,w2)

# Define loss function and back-propagation
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=y,labels=y_))
optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
train_step = optimizer.minimize(cross_entropy)

# Create dataset
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size,2) # shape is (128,2)
Y = [[int(x1+x2 < 1)] for (x1,x2) in X]

# Create Session and run the tensorflow program
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print("The parameters of pre-training:")
    print(sess.run(w1))
    print(sess.run(w2))
    
    steps = 5000
    for i in range(steps):
        # Pick up the number of batch_size data to train
        start = (i*batch_size) % dataset_size
        end = min(start+batch_size, dataset_size)
        
        # Training and update parameters
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
        
        if i % 1000 == 0:
            # output the cross entropy per 1000 times run
            total_cross_entropy = sess.run(cross_entropy,feed_dict={x:X,y_:Y})
            print("After %d training steps, cross entropy on all data is %f" %
                 (i, total_cross_entropy))

    print("The parameters of post-training:")
    print(sess.run(w1))
    print(sess.run(w2))

The parameters of pre-training:
[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
After 0 training steps, cross entropy on all data is 0.000000
After 1000 training steps, cross entropy on all data is 0.000000
After 2000 training steps, cross entropy on all data is 0.000000
After 3000 training steps, cross entropy on all data is 0.000000
After 4000 training steps, cross entropy on all data is 0.000000
The parameters of post-training:
[[-5.279851  -3.988896   6.2413116]
 [-7.063293  -5.5635242  6.979249 ]]
[[ 4.7865815]
 [ 6.1796417]
 [-6.0409307]]


In [11]:
print(X)

[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01]
 [4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01]
 [2.73875932e-02 6.70467510e-01]
 [4.17304802e-01 5.58689828e-01]
 [1.40386939e-01 1.98101489e-01]
 [8.00744569e-01 9.68261576e-01]
 [3.13424178e-01 6.92322616e-01]
 [8.76389152e-01 8.94606664e-01]
 [8.50442114e-02 3.90547832e-02]
 [1.69830420e-01 8.78142503e-01]
 [9.83468338e-02 4.21107625e-01]
 [9.57889530e-01 5.33165285e-01]
 [6.91877114e-01 3.15515631e-01]
 [6.86500928e-01 8.34625672e-01]
 [1.82882773e-02 7.50144315e-01]
 [9.88861089e-01 7.48165654e-01]
 [2.80443992e-01 7.89279328e-01]
 [1.03226007e-01 4.47893526e-01]
 [9.08595503e-01 2.93614148e-01]
 [2.87775339e-01 1.30028572e-01]
 [1.93669579e-02 6.78835533e-01]
 [2.11628116e-01 2.65546659e-01]
 [4.91573159e-01 5.33625451e-02]
 [5.74117605e-01 1.46728575e-01]
 [5.89305537e-01 6.99758360e-01]
 [1.023344